version: "3.7"

services:
  postgresql:
    container_name: "postgresql-db"
    image: postgres:latest
    volumes:
      - "/var/lib/postgresql:/var/lib/postgresql"
    restart: always
    environment:
      - POSTGRES_USER: "postgres"
      - POSTGRES_PASSWORD: "secret"
      - POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"

  mysql:
    container_name: "mysql-db"
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - "/var/lib/mysql:/var/lib/mysql"
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD: "root" # root superuser password
      - MYSQL_USER: "mysql"
      - MYSQL_PASSWORD: "secret"
      - MYSQL_DATABASE: "mysql"
    ports:
      - "3306:3306"

  mongo:
    container_name: mongo-db
    image: mongo:latest
    volumes:
      - "/var/lib/mongo:/data"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME: "mongo"
      - MONGO_INITDB_ROOT_PASSWORD: "secret"
      - MONGO_INITDB_DATABASE: "mongo"
    ports:
      - "27017:27017"

  redis:
    container_name: redis-cache
    image: redis:latest
    volumes: 
      - "var/lib/redis:/data"
    restart: always
    ports:
      - "6379:6379"

    